In [1]:
# Importing Essential Libraries

import pandas as pd 
import numpy as np


# for handling json values
import json
from pandas.io.json import json_normalize

from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reading the dataset
df= pd.read_csv("/content/drive/MyDrive/Internship/train/train.csv")
pd.set_option('display.max_columns', None)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# Getting a glimpse of dataset

df.head(3)

,channelGrouping,date,device,fullVisitorId,geoNetwork,sessionId,socialEngagementType,totals,trafficSource,visitId,visitNumber,visitStartTime
0,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",1131660440785968503,"{""continent"": ""Asia"", ""subContinent"": ""Western...",1131660440785968503_1472830385,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472830385,1,1472830385
1,Organic Search,20160902,"{""browser"": ""Firefox"", ""browserVersion"": ""not ...",377306020877927890,"{""continent"": ""Oceania"", ""subContinent"": ""Aust...",377306020877927890_1472880147,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472880147,1,1472880147
2,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",3895546263509774583,"{""continent"": ""Europe"", ""subContinent"": ""South...",3895546263509774583_1472865386,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472865386,1,1472865386

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903653 entries, 0 to 903652
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   channelGrouping       903653 non-null  object
 1   date                  903653 non-null  int64
 2   device                903653 non-null  object
 3   fullVisitorId         903653 non-null  object
 4   geoNetwork            903653 non-null  object
 5   sessionId             903653 non-null  object
 6   socialEngagementType  903653 non-null  object
 7   totals                903653 non-null  object
 8   trafficSource         903653 non-null  object
 9   visitId               903653 non-null  int64
 10  visitNumber           903653 non-null  int64
 11  visitStartTime        903653 non-null  int64
dtypes: int64(4), object(8)
memory usage: 82.7+ MB

From the above preview we can clearly see that the dataste contains JSON 
values which needed to be converted to dataframe first.

In [5]:
# function to convert json columns to dataframe

def json_to_dataframe(data, json_columns):
  for column in json_columns:
    column_to_df= json_normalize([json.loads(x) for x in data[column]])
    data= data.drop(column, axis=1).merge(column_to_df, right_index=True, left_index=True)
  return data

In [6]:
json_columns = ['device', 'geoNetwork', 'totals', 'trafficSource']
df=json_to_dataframe(df, json_columns)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

In [7]:
df.head(3)

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,browser,browserVersion,browserSize,operatingSystem,operatingSystemVersion,isMobile,mobileDeviceBranding,mobileDeviceModel,mobileInputSelector,mobileDeviceInfo,mobileDeviceMarketingName,flashVersion,language,screenColors,screenResolution,deviceCategory,continent,subContinent,country,region,metro,city,cityId,networkDomain,latitude,longitude,networkLocation,visits,hits,pageviews,bounces,newVisits,transactionRevenue,campaign,source,medium,keyword,adwordsClickInfo.criteriaParameters,isTrueDirect,referralPath,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,adContent,campaignCode
0,Organic Search,20160902,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Western Asia,Turkey,Izmir,(not set),Izmir,not available in demo dataset,ttnet.com.tr,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20160902,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Firefox,not available in demo dataset,not available in demo dataset,Macintosh,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Oceania,Australasia,Australia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,dodo.net.au,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20160902,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Southern Europe,Spain,Community of Madrid,(not set),Madrid,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Defining a function to describe each column

def dataDescription(dataframe):
  print("DataSet Shape: ", dataframe.shape)
  description= pd.DataFrame(dataframe.dtypes, columns=['dtypes'])
  description= description.reset_index()
  description['Name Of Column']= description['index']
  description= description[['Name Of Column', 'dtypes']]
  description['Missing Values']= dataframe.isnull().sum().values
  description['Unique Values']= dataframe.nunique().values

  return description

In [9]:
dataDescription(df)

DataSet Shape:  (903653, 55)

                         Name Of Column  dtypes  Missing Values  Unique Values
0                       channelGrouping  object               0              8
1                                  date   int64               0            366
2                         fullVisitorId  object               0         742735
3                             sessionId  object               0         902755
4                  socialEngagementType  object               0              1
5                               visitId   int64               0         886303
6                           visitNumber   int64               0            384
7                        visitStartTime   int64               0         887159
8                               browser  object               0             54
9                        browserVersion  object               0              1
10                          browserSize  object               0              1
11                      operatingSystem  object               0             20
12               operatingSystemVersion  object               0              1
13                             isMobile    bool               0              2
14                 mobileDeviceBranding  object               0              1
15                    mobileDeviceModel  object               0              1
16                  mobileInputSelector  object               0              1
17                     mobileDeviceInfo  object               0              1
18            mobileDeviceMarketingName  object               0              1
19                         flashVersion  object               0              1
20                             language  object               0              1
21                         screenColors  object               0              1
22                     screenResolution  object               0              1
23                       deviceCategory  object               0              3
24                            continent  object               0              6
25                         subContinent  object               0             23
26                              country  object               0            222
27                               region  object               0            376
28                                metro  object               0             94
29                                 city  object               0            649
30                               cityId  object               0              1
31                        networkDomain  object               0          28064
32                             latitude  object               0              1
33                            longitude  object               0              1
34                      networkLocation  object               0              1
35                               visits  object               0              1
36                                 hits  object               0            274
37                            pageviews  object             100            213
38                              bounces  object          453023              1
39                            newVisits  object          200593              1
40                   transactionRevenue  object          892138           5332
41                             campaign  object               0             10
42                               source  object               0            380
43                               medium  object               0              7
44                              keyword  object          502929           3659
45  adwordsClickInfo.criteriaParameters  object               0              1
46                         isTrueDirect  object          629648              1
47                         referralPath  object          572712           1475
48                adwordsClickInfo.page  object          882193              8
49                adwordsClickInfo.slot  object          882193              2
50               adwordsClickInfo.gclId  object          882092          17774
51       adwordsClickInfo.adNetworkType  object          882193              2
52           adwordsClickInfo.isVideoAd  object          882193              1
53                            adContent  object          892707             44
54                         campaignCode  object          903652              1

From the above description it is clear that many columns are having null values.

In [10]:
# Function for analysing the null values

def null_column_count(df):
    df_null = df.isnull().sum().sort_values(ascending = False).rename('Null').reset_index()

    null_count = df_null['Null']
    null_percent = (null_count * 100) / (df.shape[0])

    df_null = pd.concat([df_null['index'],null_count,null_percent], axis=1, keys=['Column','Null_Count','Null_Percent'])

    return df_null[df_null['Null_Count'] != 0]

In [11]:
null_column_count(df)

                            Column  Null_Count  Null_Percent
0                     campaignCode      903652     99.999889
1                        adContent      892707     98.788694
2               transactionRevenue      892138     98.725728
3       adwordsClickInfo.isVideoAd      882193     97.625195
4   adwordsClickInfo.adNetworkType      882193     97.625195
5            adwordsClickInfo.slot      882193     97.625195
6            adwordsClickInfo.page      882193     97.625195
7           adwordsClickInfo.gclId      882092     97.614018
8                     isTrueDirect      629648     69.678073
9                     referralPath      572712     63.377425
10                         keyword      502929     55.655102
11                         bounces      453023     50.132407
12                       newVisits      200593     22.198012
13                       pageviews         100      0.011066

The above tables shows that many columns are having more than 90% Null Values.

In [12]:
# Describing a function to fill NULL Values

def fill_null(dataframe):
  dataframe['pageviews'].fillna(1, inplace=True)
  dataframe['newVisits'].fillna(0, inplace=True)
  dataframe['bounces'].fillna(0, inplace=True) 
  dataframe["transactionRevenue"].fillna(0.0, inplace=True)


  # Converting the datatype from object to necessary
  dataframe['pageviews'] = dataframe['pageviews'].astype(int)
  dataframe['newVisits'] = dataframe['newVisits'].astype(int)
  dataframe['bounces'] = dataframe['bounces'].astype(int)
  dataframe["transactionRevenue"] = dataframe["transactionRevenue"].astype(float)
  dataframe['fullVisitorId'] = dataframe['fullVisitorId'].astype(float)
  dataframe['sessionId'] = dataframe['sessionId'].astype(float)


  dataframe['isTrueDirect'].fillna(False, inplace=True) 
  dataframe['adwordsClickInfo.isVideoAd'].fillna(True, inplace=True) # filling boolean with True
  dataframe[df['city'] == "(not set)"]['city'] = np.nan
  dataframe['city'].fillna("NaN", inplace=True)

  return dataframe

In [13]:
# Function to drop Null Columns
def drop_null(dataframe):
  dataframe.drop(list(null_column_count(dataframe)['Column']), axis=1,inplace=True)
  return dataframe

In [14]:
df= fill_null(df)
df= drop_null(df)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

The above functions will impute nan values in columns which are having null percent less than 60%, rest will be dropped execpt TransactionRevenue.

In [15]:
# Handling the datetime column

def date_time(dataframe):
  dataframe["date"] = pd.to_datetime(dataframe["date"], format="%Y%m%d") # seting the column as pandas datetime
  dataframe["weekday"] = dataframe['date'].dt.weekday #extracting week day
  dataframe["day"] = dataframe['date'].dt.day # extracting day
  dataframe["month"] = dataframe['date'].dt.month # extracting day
  dataframe["year"] = dataframe['date'].dt.year # extracting day
  dataframe['visitHour'] = (dataframe['visitStartTime'].apply(lambda x: str(datetime.fromtimestamp(x).hour))).astype(int)
    
  return dataframe

In [16]:
date_time(df)

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,browser,browserVersion,browserSize,operatingSystem,operatingSystemVersion,isMobile,mobileDeviceBranding,mobileDeviceModel,mobileInputSelector,mobileDeviceInfo,mobileDeviceMarketingName,flashVersion,language,screenColors,screenResolution,deviceCategory,continent,subContinent,country,region,metro,city,cityId,networkDomain,latitude,longitude,networkLocation,visits,hits,pageviews,bounces,newVisits,transactionRevenue,campaign,source,medium,adwordsClickInfo.criteriaParameters,isTrueDirect,adwordsClickInfo.isVideoAd,weekday,day,month,year,visitHour
0,Organic Search,2016-09-02,1.131660e+18,1.131660e+28,Not Socially Engaged,1472830385,1,1472830385,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Western Asia,Turkey,Izmir,(not set),Izmir,not available in demo dataset,ttnet.com.tr,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,0.0,(not set),google,organic,not available in demo dataset,False,True,4,2,9,2016,15
1,Organic Search,2016-09-02,3.773060e+17,3.773060e+27,Not Socially Engaged,1472880147,1,1472880147,Firefox,not available in demo dataset,not available in demo dataset,Macintosh,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Oceania,Australasia,Australia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,dodo.net.au,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,0.0,(not set),google,organic,not available in demo dataset,False,True,4,2,9,2016,5
2,Organic Search,2016-09-02,3.895546e+18,3.895546e+28,Not Socially Engaged,1472865386,1,1472865386,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Southern Europe,Spain,Community of Madrid,(not set),Madrid,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,0.0,(not set),google,organic,not available in demo dataset,False,True,4,2,9,2016,1
3,Organic Search,2016-09-02,4.763447e+18,4.763447e+28,Not Socially Engaged,1472881213,1,1472881213,UC Browser,not available in demo dataset,not available in demo dataset,Linux,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,0.0,(not set),google,organic,not available in demo dataset,False,True,4,2,9,2016,5
4,Organic Search,2016-09-02,2.729444e+16,2.729444e+26,Not Socially Engaged,1472822600,2,1472822600,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Europe,Northern Europe,United Kingdom,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,0,0.0,(not set),google,organic,not available in demo dataset,True,True,4,2,9,2016,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903648,Social,2017-01-04,5.123779e+18,5.123779e+28,Not Socially Engaged,1483554750,1,1483554750,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Caribbean,Puerto Rico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,prtc.net,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,17,15,0,1,0.0,(not set),youtube.com,referral,not available in demo dataset,False,True,2,4,1,2017,18
903649,Social,2017-01-04,7.231729e+18,7.231729e+28,Not Socially Engaged,1483543798,1,1483543798,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Southern Asia,Sri Lanka,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,18,13,0,1,0.0,(not set),youtube.com,referral,not available in demo dataset,False,True,2,4,1,2017,15
903650,Social,2017-01-04,5.744577e+18,5.744577e+28,Not Socially Engaged,1483526434,1,1483526434,Android Webview,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Eastern Asia,South Korea,Seoul,(not set),Seoul,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,24,21,0,1,0.0,(not set),youtube.com,referral,not available in demo dataset,False,True,2,4,1,2017,10
903651,Social,2017-01-04,2.709355e+18,2.709355e+28,Not Socially Engaged,1483592857,1,1483592864,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,24,22,0,1,0.0,(not set),facebook.com,referral,not available in demo dataset,False,True,2,4,1,2017,5
903652,Social,2017-01-04,8.149002e+17,8.149002e+27,Not Socially Engaged,1483574474,1,1483574474,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Americas,Central America,Mexico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,cybercable.net.mx,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,31,31,0,1,0.0,(not set),youtube.com,referral,not available in demo dataset,False,True,2,4,1,2017,0

Columns having constant or single values will also be removed here.

In [17]:
# Removing Columns that have only single unique value

def rem_cols(dataframe):
  constant_columns = [col for col in dataframe.columns if dataframe[col].nunique() == 1]
  print(f'Columns : {constant_columns}, \n Num of Columns : {len(constant_columns)}')
  dataframe.drop(constant_columns, axis=1, inplace=True)

  return dataframe

In [18]:
rem_cols(df)

Columns : ['socialEngagementType', 'browserVersion', 'browserSize', 'operatingSystemVersion', 'mobileDeviceBranding', 'mobileDeviceModel', 'mobileInputSelector', 'mobileDeviceInfo', 'mobileDeviceMarketingName', 'flashVersion', 'language', 'screenColors', 'screenResolution', 'cityId', 'latitude', 'longitude', 'networkLocation', 'visits', 'adwordsClickInfo.criteriaParameters'],
 Num of Columns : 19

,channelGrouping,date,fullVisitorId,sessionId,visitId,visitNumber,visitStartTime,browser,operatingSystem,isMobile,deviceCategory,continent,subContinent,country,region,metro,city,networkDomain,hits,pageviews,bounces,newVisits,transactionRevenue,campaign,source,medium,isTrueDirect,adwordsClickInfo.isVideoAd,weekday,day,month,year,visitHour
0,Organic Search,2016-09-02,1.131660e+18,1.131660e+28,1472830385,1,1472830385,Chrome,Windows,False,desktop,Asia,Western Asia,Turkey,Izmir,(not set),Izmir,ttnet.com.tr,1,1,1,1,0.0,(not set),google,organic,False,True,4,2,9,2016,15
1,Organic Search,2016-09-02,3.773060e+17,3.773060e+27,1472880147,1,1472880147,Firefox,Macintosh,False,desktop,Oceania,Australasia,Australia,not available in demo dataset,not available in demo dataset,not available in demo dataset,dodo.net.au,1,1,1,1,0.0,(not set),google,organic,False,True,4,2,9,2016,5
2,Organic Search,2016-09-02,3.895546e+18,3.895546e+28,1472865386,1,1472865386,Chrome,Windows,False,desktop,Europe,Southern Europe,Spain,Community of Madrid,(not set),Madrid,unknown.unknown,1,1,1,1,0.0,(not set),google,organic,False,True,4,2,9,2016,1
3,Organic Search,2016-09-02,4.763447e+18,4.763447e+28,1472881213,1,1472881213,UC Browser,Linux,False,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,1,1,1,1,0.0,(not set),google,organic,False,True,4,2,9,2016,5
4,Organic Search,2016-09-02,2.729444e+16,2.729444e+26,1472822600,2,1472822600,Chrome,Android,True,mobile,Europe,Northern Europe,United Kingdom,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,1,1,1,0,0.0,(not set),google,organic,True,True,4,2,9,2016,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903648,Social,2017-01-04,5.123779e+18,5.123779e+28,1483554750,1,1483554750,Chrome,Windows,False,desktop,Americas,Caribbean,Puerto Rico,not available in demo dataset,not available in demo dataset,not available in demo dataset,prtc.net,17,15,0,1,0.0,(not set),youtube.com,referral,False,True,2,4,1,2017,18
903649,Social,2017-01-04,7.231729e+18,7.231729e+28,1483543798,1,1483543798,Chrome,Android,True,mobile,Asia,Southern Asia,Sri Lanka,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,18,13,0,1,0.0,(not set),youtube.com,referral,False,True,2,4,1,2017,15
903650,Social,2017-01-04,5.744577e+18,5.744577e+28,1483526434,1,1483526434,Android Webview,Android,True,mobile,Asia,Eastern Asia,South Korea,Seoul,(not set),Seoul,unknown.unknown,24,21,0,1,0.0,(not set),youtube.com,referral,False,True,2,4,1,2017,10
903651,Social,2017-01-04,2.709355e+18,2.709355e+28,1483592857,1,1483592864,Chrome,Windows,False,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,24,22,0,1,0.0,(not set),facebook.com,referral,False,True,2,4,1,2017,5
903652,Social,2017-01-04,8.149002e+17,8.149002e+27,1483574474,1,1483574474,Chrome,Android,True,mobile,Americas,Central America,Mexico,not available in demo dataset,not available in demo dataset,not available in demo dataset,cybercable.net.mx,31,31,0,1,0.0,(not set),youtube.com,referral,False,True,2,4,1,2017,0

In [19]:
dataDescription(df)

DataSet Shape:  (903653, 33)

                Name Of Column          dtypes  Missing Values  Unique Values
0              channelGrouping          object               0              8
1                         date  datetime64[ns]               0            366
2                fullVisitorId         float64               0         714167
3                    sessionId         float64               0         714168
4                      visitId           int64               0         886303
5                  visitNumber           int64               0            384
6               visitStartTime           int64               0         887159
7                      browser          object               0             54
8              operatingSystem          object               0             20
9                     isMobile            bool               0              2
10              deviceCategory          object               0              3
11                   continent          object               0              6
12                subContinent          object               0             23
13                     country          object               0            222
14                      region          object               0            376
15                       metro          object               0             94
16                        city          object               0            649
17               networkDomain          object               0          28064
18                        hits          object               0            274
19                   pageviews           int64               0            213
20                     bounces           int64               0              2
21                   newVisits           int64               0              2
22          transactionRevenue         float64               0           5333
23                    campaign          object               0             10
24                      source          object               0            380
25                      medium          object               0              7
26                isTrueDirect            bool               0              2
27  adwordsClickInfo.isVideoAd            bool               0              2
28                     weekday           int64               0              7
29                         day           int64               0             31
30                       month           int64               0             12
31                        year           int64               0              2
32                   visitHour           int64               0             24